pipeline {

    agent any

    tools {

        maven 'Maven3'

    }

    environment {

        IMAGE_NAME = "jabhii26/studentportal"

        IMAGE_TAG = "${BUILD_NUMBER}"

    }

    stages {

        stage('Checkout') {

            steps {

                checkout scm

            }

        }

        stage('Build') {

            steps {

                bat 'mvn compile'

            }

        }

        stage('Test') {

            steps {

                bat 'mvn test'

            }

        }

        stage('Docker Build') {

            steps {

                script {

                    image = docker.build(
                        "${IMAGE_NAME}:${IMAGE_TAG}"
                    )

                }

            }

        }

        stage('Docker Push') {

            steps {

                script {

                    docker.withRegistry(
                        'https://registry.hub.docker.com',
                        'dockerhub-creds'
                    ) {

                        image.push()

                    }

                }

            }

        }

    }

}