pipeline {

    agent any

    tools {

        maven 'maven3'

    }

    environment {

        IMAGE_NAME = "jabhii26/studentportal"

        IMAGE_TAG = "${BUILD_NUMBER}"

    }

    stages {

        stage('Checkout') {

            steps {

                checkout scm

            }

        }

        stage('Build') {

            steps {
                dir('Docker_jenkins') {
                    bat 'mvn compile'
                }
            }

        }

        stage('Test') {

            steps {
                dir('Docker_jenkins') {
                    bat 'mvn test'
                }
            }

        }

        stage('Docker Build') {

            steps {
                dir('Docker_jenkins') {
                    script {

                        image = docker.build(
                            "${IMAGE_NAME}:${IMAGE_TAG}"
                        )

                    }
                }
            }

        }

        stage('Docker Push') {

            steps {

                script {

                    docker.withRegistry(
                        'https://registry.hub.docker.com',
                        'dockerhub-creds'
                    ) {

                        image.push()

                    }

                }

            }

        }

    }

}