pipeline {

    agent any

    tools {

        maven 'Maven3'

    }

    environment {

        IMAGE_NAME = "YOUR_DOCKERHUB_USERNAME/studentportal"

        IMAGE_TAG = "${BUILD_NUMBER}"

    }

    stages {

        stage('Build') {

            steps {

                bat 'mvn clean package'

            }

        }

        stage('Docker Build') {

            steps {

                script {

                    docker.build(
                        "${IMAGE_NAME}:${IMAGE_TAG}"
                    )

                }

            }

        }

        stage('Docker Push') {

            steps {

                script {

                    docker.withRegistry(
                        'https://registry.hub.docker.com',
                        'dockerhub-creds'
                    ) {

                        docker.image(
                            "${IMAGE_NAME}:${IMAGE_TAG}"
                        ).push()

                    }

                }

            }

        }

    }

}