pipeline {

    agent any

    tools {

        maven 'maven3'

    }

    environment {

        IMAGE_NAME = "jabhii26/studentportal"

        IMAGE_TAG = "${BUILD_NUMBER}"

    }

    stages {

        stage('Build') {

            steps {

                dir('Practical07') {

                    bat 'mvn clean package'

                }

            }

        }

        stage('Docker Build') {

            steps {

                dir('Practical07') {

                    script {

                        docker.build(
                            "${IMAGE_NAME}:${IMAGE_TAG}"
                        )

                    }

                }

            }

        }

        stage('Docker Push') {

            steps {

                script {

                    docker.withRegistry(
                        'https://registry.hub.docker.com',
                        'dockerhub-creds'
                    ) {

                        docker.image(
                            "${IMAGE_NAME}:${IMAGE_TAG}"
                        ).push()

                    }

                }

            }

        }

    }

}