pipeline {

    agent any

    tools {
        maven 'Maven3'
    }

    stages {

        stage('Compile') {
            steps {
                bat 'mvn compile'
            }
        }

        stage('Test') {
            steps {
                bat 'mvn test'
            }
        }

    }

    post {

        always {

            junit '**/target/surefire-reports/*.xml'

        }

    }
}
